- name: Install and configure New Relic Infrastructure agent
  hosts: all              # matches any host provided via -i
  become: yes             # run tasks as root
  gather_facts: yes       # collect system info (OS, packages, etc.)
  vars:
    license_key: "{{ lookup('env', 'NEW_RELIC_LICENSE_KEY') }}"  # from GitHub Secrets
  tasks:
    - name: Ensure apt-transport-https is installed
      apt:
        name: apt-transport-https
        state: present
        update_cache: yes

    - name: Add New Relic GPG key
      ansible.builtin.apt_key:
        url: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
        state: present

    - name: Add New Relic apt repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt {{ ansible_distribution_release }} main"
        state: present

    - name: Install New Relic Infrastructure agent
      ansible.builtin.apt:
        name: newrelic-infra
        state: present
        update_cache: yes

    - name: Configure New Relic license key
      ansible.builtin.copy:
        dest: /etc/newrelic-infra.yml
        content: |
          license_key: {{ license_key }}
        owner: root
        group: root
        mode: '0600'

    - name: Ensure New Relic service is running
      ansible.builtin.systemd:
        name: newrelic-infra
        state: started
        enabled: yes
