---
- name: Install and configure New Relic Infrastructure agent
  hosts: all
  become: yes
  vars:
    license_key: "{{ NEW_RELIC_LICENSE_KEY }}"   # passed from GitHub Secret
  tasks:
    - name: Add New Relic repo
      apt_key:
        url: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
        state: present

    - name: Add New Relic apt repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt {{ ansible_distribution_release }} main"
        state: present

    - name: Install New Relic agent
      apt:
        name: newrelic-infra
        state: present
        update_cache: yes

    - name: Configure New Relic license key
      copy:
        dest: /etc/newrelic-infra.yml
        content: |
          license_key: {{ license_key }}

    - name: Ensure New Relic service is running
      systemd:
        name: newrelic-infra
        state: started
        enabled: yes
