- name: Install and configure New Relic Infrastructure + Java Agent
  hosts: all
  become: yes
  vars:
    license_key: "{{ lookup('env', 'NEW_RELIC_LICENSE_KEY') }}"
    region: "{{ lookup('env', 'NEW_RELIC_REGION') | default('US') }}"
    app_dir: "/home/ubuntu/spring-petclinic"

  tasks:
    # -------------------------------
    # Infrastructure Agent (System Metrics)
    # -------------------------------
    - name: Ensure dependencies are installed
      apt:
        name:
          - apt-transport-https
          - curl
        state: present
        update_cache: yes

    - name: Add New Relic GPG key
      ansible.builtin.apt_key:
        url: https://download.newrelic.com/infrastructure_agent/gpg/newrelic-infra.gpg
        state: present

    - name: Add New Relic apt repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.newrelic.com/infrastructure_agent/linux/apt {{ ansible_distribution_release | lower }} main"
        state: present

    - name: Install New Relic Infrastructure agent
      ansible.builtin.apt:
        name: newrelic-infra
        state: present
        update_cache: yes

    - name: Configure New Relic license key and region
      copy:
        dest: /etc/newrelic-infra.yml
        content: |
          license_key: {{ license_key }}
          {% if region == 'EU' %}
          region: EU
          {% endif %}
        owner: root
        group: root
        mode: '0600'

    - name: Restart New Relic Infrastructure agent
      ansible.builtin.systemd:
        name: newrelic-infra
        state: restarted
        enabled: yes

    # -------------------------------
    # Java Agent (Application Metrics)
    # -------------------------------
    - name: Ensure unzip is installed
      apt:
        name: unzip
        state: present
        update_cache: yes

    - name: Download New Relic Java agent
      get_url:
        url: https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip
        dest: /tmp/newrelic-java.zip

    - name: Unzip Java agent
      unarchive:
        src: /tmp/newrelic-java.zip
        dest: /opt/
        remote_src: yes
        creates: /opt/newrelic/newrelic.jar

    - name: Configure New Relic Java agent
      copy:
        dest: /opt/newrelic/newrelic.yml
        content: |
          common: &default_settings
            license_key: {{ license_key }}
            app_name: SpringPetClinic
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Ensure Spring Boot app directory exists
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Start Spring Boot app with New Relic agent
      shell: |
        pkill -f spring-petclinic || true
        nohup java -javaagent:/opt/newrelic/newrelic.jar -jar {{ app_dir }}/target/*.jar > {{ app_dir }}/app.log 2>&1 &
      args:
        chdir: "{{ app_dir }}"
