- name: Install and configure New Relic Infrastructure and Java agents
  hosts: all
  become: yes
  vars:
    license_key: "{{ lookup('env', 'NEW_RELIC_LICENSE_KEY') }}"
    region: "{{ lookup('env', 'NEW_RELIC_REGION') | default('US') }}"
    app_dir: "/home/ubuntu/spring-petclinic"

  roles:
    - role: newrelic.newrelic-infra
      vars:
        nrinfragent_config:
          license_key: "{{ license_key }}"
          {% if region == 'EU' %}
          region: EU
          {% endif %}
        nrinfragent_service_state: started
        nrinfragent_service_enabled: yes

  tasks:
    - name: Ensure unzip is installed
      apt:
        name: unzip
        state: present
        update_cache: yes

    - name: Download New Relic Java agent
      get_url:
        url: https://download.newrelic.com/newrelic/java-agent/newrelic-agent/current/newrelic-java.zip
        dest: /tmp/newrelic-java.zip
        mode: '0644'

    - name: Unarchive New Relic Java agent
      unarchive:
        src: /tmp/newrelic-java.zip
        dest: /opt/
        remote_src: yes
        creates: /opt/newrelic/newrelic.jar

    - name: Configure New Relic Java agent
      copy:
        dest: /opt/newrelic/newrelic.yml
        content: |
          common: &default_settings
            license_key: {{ license_key }}
            app_name: SpringPetClinic
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Ensure Spring Boot app directory exists
      file:
        path: "{{ app_dir }}"
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Start Spring Boot app with New Relic Java agent
      shell: |
        pkill -f spring-petclinic || true
        nohup java -javaagent:/opt/newrelic/newrelic.jar -jar {{ app_dir }}/target/*.jar > {{ app_dir }}/app.log 2>&1 &
      args:
        chdir: "{{ app_dir }}"
