# .github/workflows/install-newrelic.yml

name: Install New Relic on Existing Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible python3-apt sshpass unzip

      - name: Run Ansible Playbook
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
          NEW_RELIC_REGION: ${{ secrets.NEW_RELIC_REGION }}
          SERVER_USER: ubuntu
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook ansible/install-newrelic.yml \
            -i "${SERVER_IP}," \
            -u "${SERVER_USER}" \
            --private-key private_key.pem
