# .github/workflows/deploy-newrelic.yml

name: Deploy New Relic Agents

on:
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Install Ansible and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible python3-apt unzip sshpass

      - name: Run Ansible Playbook
        env:
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
          NEW_RELIC_REGION: ${{ secrets.NEW_RELIC_REGION }}
          ANSIBLE_HOST_KEY_CHECKING: "False"
        run: |
          ansible-playbook ansible/install-newrelic.yml \
            -i "${{ secrets.SERVER_IP }}," \
            -u ubuntu \
            --private-key private_key.pem
