name: Install New Relic on Existing Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible python3-apt sshpass

      - name: Run Ansible Playbook with .env and Secrets
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
        run: |
          # Load .env variables (SERVER_IP, SERVER_USER)
          export $(grep -v '^#' .env | xargs)
          echo "Using server: $SERVER_USER@$SERVER_IP"

          # Save SSH key
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Run the Ansible playbook (adjust path to playbook folder)
          ansible-playbook ansible/install-newrelic.yml \
            -i "${SERVER_IP}," \
            -u "${SERVER_USER}" \
            --private-key private_key.pem
