name: Install New Relic on Existing Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build Spring Boot app
        run: ./mvnw clean package -DskipTests
        working-directory: ./spring-petclinic

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible python3-apt sshpass unzip

      - name: Run Ansible Playbook with .env and Secrets
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
          NEW_RELIC_REGION: ${{ secrets.NEW_RELIC_REGION }} # Optional: US or EU
        run: |
          # Load .env variables
          if [ -f .env ]; then
            export $(grep -v '^#' .env | xargs)
          fi
          echo "Using server: $SERVER_USER@$SERVER_IP"

          # Save SSH key
          echo "$SSH_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Disable host key checking for Ansible
          export ANSIBLE_HOST_KEY_CHECKING=False

          # Run Ansible playbook
          ansible-playbook ansible/install-newrelic.yml \
            -i "${SERVER_IP}," \
            -u "${SERVER_USER}" \
            --private-key private_key.pem
